# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

development:
  adapter: postgresql
  encoding: utf8
  database: music_development
  pool: 5
  username: postgres
  password: qwerty123

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: music_test
  pool: 5
  username: postgres
  password: qwerty123

production:
  adapter: postgresql
  encoding: utf8
  database: music_production
  pool: 5
  username: postgres
  password: qwerty123

cucumber:
  <<: *TEST
